# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3473a2e932dd81b7a0a83a9e8fcb296241e72aa07756e449f454b4f513103833257e88d62052597015eaa82708a9481bcf7336753675c00364957e72102dfec

test:
  secret_key_base: ee6bccf88f8499210cbd8f044f9636761d110bb528d6624bab07cb220a3a01458b6a568cfdb531300895829947f74c29f9c8eb9a0a654e90290922e645d95d0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
